artifact_uri: file:C:\Users\1234\Documents\Especialización\Segundo semestre\Producto
  de datos\Sesion 7\PRE-08-mlflow-tracking-local-matorop\my_mlruns/260769639970575283/85e7dbca3bac49bdaaf4f05e6f66b4b1/artifacts
end_time: 1748101488503
entry_point_name: ''
experiment_id: '260769639970575283'
lifecycle_stage: active
run_id: 85e7dbca3bac49bdaaf4f05e6f66b4b1
run_name: knn_9497fd4d
run_uuid: 85e7dbca3bac49bdaaf4f05e6f66b4b1
source_name: ''
source_type: 4
source_version: ''
start_time: 1748101488371
status: 3
tags: []
user_id: '1234'
